
Description: |
  This stack automates the creation of Bedrock Knowledge Base, Data Source, 
  Agent, AgentAlias, Guardrail and GuardrailVersion
  
Parameters:
  OpenSearchCollectionARN:
    Type: String
    Description: OpenSearch Service Serverless (AOSS) collection ARN
    
  EmbeddingModelArn:
    Type: String
    Description: Knowledge Base Model Arn, can get it by using $aws bedrock list-foundation-models 
    
  AOSSIndexName:
    Type: String
    Description: Name of the vector index in the Amazon OpenSearch Service Serverless (AOSS) collection
    
  VectorField:
    Type: String
    Description: Provide a name for the field
    
  TextField:
    Type: String
    Description: Provide additional information that a knowledge base can retrieve with vectors
    
  MetadataField:
    Type: String
    Description: Provide additional metadata that a knowledge base can retrieve with vectors
    
  KnowledgeBaseName:
    Type: String
    Description: The name of the knowledge base
    
  BedrockExecutionRoleARNForKnowledgeBase:
    Type: String
    Description: The knowledge base execution role-arn which is being trusted by your Opensearch serverless collection access-policy
  
  KnowledgeBaseDescription:
    Type: String
    Description: The description of the knowledge base
    
  DataSourceName: 
    Type: String
    Description: Name of the Bedrock DataSource
    
  DataSourceBucketName: 
    Type: String
    Description: Name of the S3 bucket which stored the DataSource
    
  AgentName: 
    Type: String
    Description: Name of the Bedrock Agent
    
  FoundationModelForAgent:
    Type: String
    Description: Foundation Model which will be used by your Bedrock Agent
    
  AgentInstruction:
    Type: String
    Description: Instruction for your Bedrock Agent
    
  AgentDescription:
    Type: String
    Description: Description for your Bedrock Agent
    
  AgentAliasName:
    Type: String
    Description: The name of the alias of the agent
    
  AgentAliasDescription:
    Type: String
    Description: The description of the alias of the agent
    
  GuardrailName: 
    Type: String
    Description: Name of the Bedrock Agent
    
  GuardrailVersionDescription:
    Type: String
    Description: A description of the guardrail version 


Resources:
  # Bedrock KnowledgeBase
  KnowledgeBaseWithAoss:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Ref KnowledgeBaseName
      Description: !Ref KnowledgeBaseDescription
      RoleArn: !Ref BedrockExecutionRoleARNForKnowledgeBase
      KnowledgeBaseConfiguration:
        Type: "VECTOR"
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Ref EmbeddingModelArn
      StorageConfiguration:
        Type: "OPENSEARCH_SERVERLESS"
        OpensearchServerlessConfiguration:
          CollectionArn: !Ref OpenSearchCollectionARN
          VectorIndexName: !Ref AOSSIndexName
          FieldMapping:
            VectorField: !Ref VectorField
            TextField: !Ref TextField
            MetadataField: !Ref MetadataField

  # Bedrock DataSource
  DataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      KnowledgeBaseId: !Ref KnowledgeBaseWithAoss
      Name: !Ref DataSourceName
      DataSourceConfiguration:
        Type: "S3"
        S3Configuration:
          BucketArn: !Sub arn:aws:s3:::${DataSourceBucketName}
      DataDeletionPolicy: DELETE

  # Bedrock Agent Role
  AmazonBedrockExecutionRoleForAgentsQA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: bedrock.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonBedrockFullAccess
  
  # Custom KMS key with a key policy For Bedrock Agent
  MyCustomKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Custom KMS Key for Bedrock Agent encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: 'Allow Amazon Bedrock to encrypt and decrypt Agent resources on behalf of authorized users'
            Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action:
              - kms:*
            Resource: "*"
          - Sid: "Allow account root to modify the KMS key"
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"

  # Bedrock Agent
  Agent:
    Type: AWS::Bedrock::Agent
    Properties:
      AgentName: !Ref AgentName
      AgentResourceRoleArn: !GetAtt AmazonBedrockExecutionRoleForAgentsQA.Arn
      AutoPrepare: true
      FoundationModel: !Ref FoundationModelForAgent
      Instruction: !Ref AgentInstruction
      Description: !Ref AgentDescription
      IdleSessionTTLInSeconds: 900
      CustomerEncryptionKeyArn: !GetAtt MyCustomKMSKey.Arn
      KnowledgeBases:
        - KnowledgeBaseId: !Ref KnowledgeBaseWithAoss
          Description: !Ref KnowledgeBaseDescription
          KnowledgeBaseState: ENABLED

  # Bedrock Agent Alias
  AgentAliasResource:
    Type: AWS::Bedrock::AgentAlias
    Properties:
      AgentId: !Ref Agent
      AgentAliasName: !Ref AgentAliasName
      Description: !Ref AgentAliasDescription

  # Bedrock Guardrail
  Guardrail:
    Type: "AWS::Bedrock::Guardrail"
    DependsOn:
      - KnowledgeBaseWithAoss
    Properties: 
      BlockedInputMessaging: "Guardrail applied based on the input."
      BlockedOutputsMessaging: "Guardrail applied based on output."
      Name: !Ref GuardrailName
      Description: "My Bedrock Guardrail created with AWS CFN"
      ContentPolicyConfig: 
        FiltersConfig: 
        - InputStrength: "HIGH"
          OutputStrength: "HIGH"
          Type: "SEXUAL"
        - InputStrength: "HIGH"
          OutputStrength: "HIGH"
          Type: "VIOLENCE"
        - InputStrength: "HIGH"
          OutputStrength: "HIGH"
          Type: "HATE"
        - InputStrength: "HIGH"
          OutputStrength: "HIGH"
          Type: "INSULTS"
        - InputStrength: "HIGH"
          OutputStrength: "HIGH"
          Type: "MISCONDUCT"
        - InputStrength: "NONE"
          OutputStrength: "NONE"
          Type: "PROMPT_ATTACK"
      SensitiveInformationPolicyConfig: 
        PiiEntitiesConfig: 
        - Action: "BLOCK"
          Type: "EMAIL"
        - Action: "ANONYMIZE"
          Type: "IP_ADDRESS"
      TopicPolicyConfig: 
        TopicsConfig: 
          - Definition: "Investment advice is inquiries, guidance, or recommendations about the management or allocation of funds or assets with the goal of generating returns or achieving specific financial objectives."
            Examples: 
              - "Is investing in the stocks better than bonds?"
              - "Should I invest in gold?"
            Name: "Investment Advice"
            Type: DENY
      WordPolicyConfig: 
        # Profanity filter
        ManagedWordListsConfig: 
          - Type: PROFANITY
        # Custom word filter
        WordsConfig: 
          - Text: BLOCKTHISWORD
      ContextualGroundingPolicyConfig: 
        FiltersConfig: 
          # Grounding score represents the confidence that the model response is factually correct and grounded in the source. If the model response has a lower score than the defined threshold, the response will be blocked and the configured blocked message will be returned to the user. A higher threshold level blocks more responses
          - Threshold: 0.8
            Type: GROUNDING
          # Relevance score represents the confidence that the model response is relevant to the user's query. If the model response has a lower score than the defined threshold, the response will be blocked and the configured blocked message will be returned to the user. A higher threshold level blocks more responses.
          - Threshold: 0.8
            Type: RELEVANCE

  # Bedrock Guardrail Version
  GuardrailVersion:
    Type: AWS::Bedrock::GuardrailVersion
    Properties:
      Description: !Ref GuardrailVersionDescription
      GuardrailIdentifier: !GetAtt Guardrail.GuardrailArn