AWSTemplateFormatVersion: '2010-09-09'
# IOT Thing Principal Attachement resource to attach a principal (an X.509 certificate or another credential) to a thing
Resources:
  MyPolicyPrincipalAttachment: 
    Type: AWS::IoT::ThingPrincipalAttachment 
    Properties:
      ThingName: ThingName1
      Principal: arn:aws:iot:us-east-1:${AWS::AccountId}:cert/db2345ef1593fb6e04a2d036d964b69d21e92828c80cc49730087a830a1d4015
            