AWSTemplateFormatVersion: '2010-09-09'
# IOT PolicyPrincipalAttachment resource to attach an AWS IoT policy to a principal (an X.509 certificate or other credential)
Resources:
  MyPolicyPrincipalAttachment: 
    Type: AWS::IoT::PolicyPrincipalAttachment 
    Properties:
      PolicyName: testPolicy
      Principal: arn:aws:iot:us-east-1:${AWS::AccountId}:cert/db2345ef1593fb6e04a2d036d964b69d21e92828c80cc49730087a830a1d4015